services:
  rnsd:
    build:
      context: ./Stable
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    volumes:
      - ./conf/reticulum.conf:/root/.reticulum/config
      - ./storage:/root/.reticulum/storage
    restart: unless-stopped
